stages:
  - test

variables:
  CLOJURE_VERSION: "1.10.1.502"

test:
  stage: test
  image: clojure:openjdk-11-tools-deps-$CLOJURE_VERSION
  cache:
    key: always
    paths:
      - .m2/
      - .cache/
      - .cpcache/
  before_script:
    - rm -rf $HOME/.m2
    - mkdir -p $CI_PROJECT_DIR/.m2
    - ln -s $CI_PROJECT_DIR/.m2 $HOME/.m2
    - cp -f settings-ci.xml $HOME/.m2/settings.xml
    - export GITLIBS=$PWD/.cache/gitlibs
    - export XDG_CACHE_HOME=$PWD/.cache
  script:
    - clojure J-Dclojure.main.report=stderr -Mtest
